MiYE/MiYE/urls.py
"""
Definition of urls for MiYE.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views
from django.urls import path, include

admin.site.site_header = 'MiYE Admin'
admin.site.index_title = 'MiYE Admin'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log in',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
    path('Reservations/', include('Reservations.urls')),
    path('Services/', include('Services.urls')),
]

MiYE/Services/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.ServicesListView.as_view(), name='services_changelist'),
    path('add/', views.ServicesCreateView.as_view(), name='services_add'),
    path('<int:pk>/', views.ServicesUpdateView.as_view(), name='services_change'),
    path('ajax/load-optiones/', views.load_optiones, name='ajax_load_optiones'),
   ]

MiYE/Services/models.py
from django.db import models

# ALWAYS run "python manage.py makemigrations" and "python manage.py migrate"
# Create your models here.


# Create your models here.
class Types(models.Model):
    name = models.CharField(max_length=30)
 
    def __str__(self):
        return self.name

class Options(models.Model):
    types = models.ForeignKey(Types, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Services(models.Model):
    THIRTY = 30
    SIXTY = 60
    NINETY = 90

    DURATION_CHOICES = [
        (THIRTY,30),
        (SIXTY,60),
        (NINETY,90)
        ]

    ONE = 1
    TWO = 2
    THREE = 3
    FOUR = 4
    FIVE = 5
    SIX = 6

    NUM_PEOPLE_CHOICE = [
        (ONE, 1),
        (TWO, 2),
        (THREE, 3),
        (FOUR, 4),
        (FIVE, 5),
        (SIX, 6)
        ]
    name = models.CharField(max_length=100) # max_length = required
    types = models.ForeignKey(Types, on_delete=models.SET_NULL, null=True)
    options = models.ForeignKey(Options, on_delete=models.SET_NULL, null=True,)
    duration = models.IntegerField(choices=DURATION_CHOICES, default=30)
    people = models.IntegerField(choices=NUM_PEOPLE_CHOICE, default=1)
    Description = models.TextField(blank=True, null=True) # blank = field req; null =>db
    Price = models.DecimalField(decimal_places=2, max_digits=10)
 
    def __str__(self):
        return self.name

MiYE/Services/forms.py
from django import forms
from .models import Services, Options

class ServicesForm(forms.ModelForm):
    class Meta:
        model = Services
        fields = ('name','types', 'options','duration','people','Description','Price')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['options'].queryset = Options.objects.none()

        if 'types' in self.data:
            try:
                types_id = int(self.data.get('types'))
                self.fields['options'].queryset = Options.objects.filter(types_id=types_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['options'].queryset = self.instance.types.options_set.order_by('name')

MiYE/Services/views.py
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from .models import Services, Options
from .forms import ServicesForm
from django.shortcuts import render

class ServicesListView(ListView):
    model = Services
    form_class = ServicesForm
    context_object_name = 'Services'

class ServicesCreateView(CreateView):
    model = Services
    form_class = ServicesForm
    success_url = reverse_lazy('services_changelist')

class ServicesUpdateView(UpdateView):
    model = Services
    form_class = ServicesForm  
    success_url = reverse_lazy('services_changelist')

def load_optiones(request):
    types_id = request.GET.get('types')
    optiones = Options.objects.filter(types_id=types_id).order_by('name')
    return render(request, 'Services/option_ddl.html', {'optiones': optiones})

MiYE/Services/templates/Services/option_ddl.html
<option value="">---------</option>
{% for option in optiones %}
<option value="{{ option.pk }}">{{ option.name }}</option>
{% endfor %}

MiYE/Services/templates/Services/services_form.html
{% extends 'base.html' %}

{% block content %}

  <h2>Booking Services</h2>

  <form method="post" id="ServicesForm" data-optiones-url="{% url 'ajax_load_optiones' %}" novalidate>
    {% csrf_token %}
    <table>
      
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <a href="{% url 'services_changelist' %}">Cancel</a>
  </form>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script>
    $("#id_types").change(function () {
      var url = $("#ServicesForm").attr("data-optiones-url");  
      var typeId = $(this).val();  

      $.ajax({                      
        url: url,                    
        data: {
          'types': typeId       
        },
        success: function (data) {  
          $("#id_options").html(data);  
        }
      });

    });
  </script>


{% endblock %}

MiYE/Services/templates/Services/services_list.html
{% extends 'base.html' %}

{% block title %}Human Resources Module{% endblock %}

{% block content %}
  <h2>Add Services</h2>

  <p>
    <a href="{% url 'services_add' %}">Add Services</a>
  </p>

  <table border="1">
    <thead>
      <tr>
        <th>Services</th>
        <th>Types</th>
        <th>Options</th>
        <th>Duration</th>
      </tr>
    </thead>
    <tbody>
      {% for service in services %}
        <tr>
          <td><a href="{% url 'services_change' service.pk %}">{{ Services.types.name }}</a></td>
          <td>{{ Services.options.name }}</td>
          <td>{{ Services.Prices }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">Services not found. <a href="{% url 'services_add' %}">Add the service</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}